import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css"; // Fondamentale per il DatePicker
import "./globals.css"; // Il tuo CSS (Tailwind) deve venire dopo
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
import DynamicBackground from '../components/DynamicBackground';
import MantineProviderClient from "../components/MantineProviderClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>extraJob</title>
      <meta name="description" content="Piattaforma di lavoro extra per studenti e lavoratori part-time" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>
      <body>
        <MantineProviderClient>
          <main className="relative z-10">
            <DynamicBackground />
            {children}
          </main>
        </MantineProviderClient>
      </body>
    </html>
  );
}

